config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #   Un utilisateur peut voir toutes les listes
  get 'lists', to: 'lists#index'

  # Un utilisateur peut créer une nouvelle liste
  get 'lists/new', to: 'lists#new', as: :new_list

  # Un utilisateur peut voir les détails d’une liste donnée et son nom
  get 'lists/:id', to: 'lists#show', as: :list

  post 'lists', to: 'lists#create'

  # ROUTES POUR MOVIES
  resources :movies, only: [:index, :show]

  # ROUTES POUR BOOKMARKS

  # Ajout new signet à une liste
  # get 'lists/:list_id/bookmarks/new', to: 'bookmarks#new', as: :new_list_bookmark
  # post 'lists/:list_id/bookmarks', to: 'bookmarks#create'

  # # Pour supprimer un signet d'une liste
  # delete 'bookmarks/:id', to: 'bookmarks#destroy'

  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

# couple (list, movie) unique -> "This movie is already bookmarked in this list."

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = @list.bookmarks.new
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully destroyed.'
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end


# class BookmarksController < ApplicationController
#   def new
#     @list = List.find(params[:list_id])
#     @bookmark = Bookmark.new
#   end

#   def create
#     @bookmark = Bookmark.new(bookmark_params)
#     @list = List.find(params[:list_id])
#     @bookmark.list = @list
#     @bookmark.save!

#     redirect_to list_path(@list)
#   end

#   def destroy
#     @bookmark = Bookmark.find(params[:id])
#     @bookmark.destroy

#     redirect_to list_path(@bookmark.list)
#   end

#   private

#   def bookmark_params
#     params.require(:bookmark).permit(:movie_id)
#   end
# end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # voir toutes les listes
  def index
    @lists = List.all
  end

  # voir détails d'une liste
  def show
    @list = List.find(params[:id])
  end

  # afficher FORMULAIRE création d'une liste
  def new
    @list = List.new
  end

  # créer une nouvelle liste
  # def create
  #   @list = List.new(list_params)
  #   @list.save!

  #   redirect_to list_path(@list)
  # end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  # Afficher tous les movies
  def index
    @movies = Movie.all
  end

  # Afficher détail d'un movie
  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new bookmark to <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark], url: list_bookmarks_path(@list) do |f| %>
  <%= f.association :movie, label: 'Choose a movie', collection: Movie.all, prompt: 'Select a movie' %>
  <%= f.input :comment, label: "Add a comment" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%# <h1> My lists </h1>

<ul>
  <% @lists.each do |list| %>

  <%# <li> <%= link_to list.name, list_path(list) %>
  <%# </li> %>
  <%# <% end %>
<%# </ul> %>

<%# <%= link_to "Create a new list", new_list_path, class: "btn btn-success" %>


<h1 class="list-title"> My Lists </h1>

<div class="list-container">
  <% @lists.each do |list| %>
    <div class="list-box">
      <%= link_to list.name, list_path(list) %>
    </div>
  <% end %>
</div>

<%= link_to "Create a new list", new_list_path, class: "btn btn-success" %>

app/views/lists/new.html.erb
<h1> Create a movie list </h1>

<%= simple_form_for @list do |f|
  <%= f.input :name, label: "Name of the list" %>
  <%= f.submit %>
 <% end %>

app/views/lists/show.html.erb
<h1 class="list-title-centered"> <%= @list.name %> </h1>


<div class="bookmark-container">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="bookmark-box">
      <img src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>" class="bookmark-poster">
      <div class="bookmark-title">
        <%= bookmark.movie.title %>
        <span class="bookmark-rating">
          - <%= bookmark.movie.rating %> <i class="fa fa-star"></i>
        </span>
      </div>
      <div class="bookmark-overview">
        <%= truncate(bookmark.movie.overview, length: 100) %>  <!-- Limitez l'aperçu à 100 caractères -->
      </div>
      <div class="bookmark-comment">
        <i class="fa fa-quote-left"></i>
        <%= bookmark.comment %>
      </div>
      <%= form_with url: list_bookmark_path(@list, bookmark), method: :delete do %>
        <%= submit_tag 'Delete', class: 'btn-delete', data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  <% end %>
</div>




<%# <% @list.bookmarks.each do |bookmark| %>
  <%# <%= bookmark.movie.title %> <%# <%= bookmark.comment %>
    <%#<%= form_with url: list_bookmark_path(@list, bookmark), method: :delete do %>
    <%#<%= submit_tag 'Delete', data: { confirm: "Are you sure?" } %>
  <%#<% end %>
<%#<% end %>

app/views/movies/index.html.erb
<h1> List of movies</h1>

<ul>
  <% @movies.each do |movie| %>
    <li>
    <%= link_to movie.title, movie_path(movie) %>
    </li>
  <% end %>
</ul>

app/views/movies/show.html.erb
<h1> <%= @movie.title %> </h1>
<p><%= @movie.overview %></p>
<img src ="<%= @movie.poster_url%>" alt ="<%= @movie.title %>">
<p>Rating: <%= @movie.rating %></p>